### PR TITLE
using cake.recipe

### PR DESCRIPTION
**Pull request by Meir017**
#9
@gep13  - https://ci.appveyor.com/project/cakecontrib/cake-openshift/build/0.3.1-improve-cake-recipe.1+3.build.3
Locally the task `DupFinder` passes but on `appveyor` it fails

### CODE REVIEW

**Comment by gep13** [comment]
Not at my computer just now, but will try to take a look once kids are in bed.

**Comment by gep13** [comment]
@Meir017 I suspect the issue that you are running into is the Build Worker Image that you are using.

Since you are doing `RunDotNetCore` you are going to want to switch to using this:

https://github.com/cake-contrib/Cake.ReSharperReports/blob/develop/.appveyor.yml#L4

Hope that helps!

**Comment by gep13** [comment]
Also, we have convention to call the entry Cake script `setup.cake`, rather than `build.cake`.

This is not a requirement, but it does make it either to reason about the build system being used on this repo.

**Comment by Meir017** [comment]
@gep13 anything else?

**Comment by gep13** [comment]
Cake.Recipe has a convention of using a SolutionInfo.cs file, which is then shared between projects, for stamping assemblies with the generated version number (it uses GitVersion to find the semantic version number, based on the history of the git repository).

Currently, looks like you are using a Shared.msbuild file to do that work.  You might want to switch away from that?

I normally call my `appveyor.yml` as `.appveyor.yml` but that is a personal preference.

Looks like your build.sh is still pointing at `build.cake`.

Other than that, looks good to me 😄

**Comment by gep13** [comment]
Oh, one other thing...

You might want to add a GitReleaseManager yml configuration file.  This helps generate the release notes.  You can find one in the repo I linked to earlier.

**Comment by Meir017** [comment]
@gep13 I created a draft for the milestone 0.3.1.
so once I complete the issues in the milestone it will release automatically and publish to NuGet?

**Comment by gep13** [comment]
@Meir017 Yes, once you publish the Draft Release on GitHub, this will cause a tag to be added to the repository.  This will trigger a build, and based on the tag being present, Cake.Recipe will do the work of pushing the nupkg to NuGet.org, rather than MyGet.org.

**Comment by Meir017** [comment]
And publishing the draft manually is only for the first time?

**Comment by gep13** [comment]
The publishing of the draft is the one manual step that needs to be carried out, everything else is done automatically.  This manual step is the final verification point, and your oppurtunity to ensure that everything is correct before pushing.  It could be automated, but I personally prefer this manual verification step.  i.e. there would be a manual step for each release that you create.

**Comment by gep13** [comment]
Obviously, you would need to merge this PR before finalising the draft release on GitHub 😄

**Comment by Meir017** [comment]
@gep13 cool - https://github.com/cake-contrib/Cake.Openshift/releases/tag/0.3.1

**Comment by gep13** [comment]
Hmm, that didn't seem to trigger a build on AppVeyor 😢 

Therefore the release won't actually happen.  Can you walk me through the exact steps that you just did?

**Comment by Meir017** [comment]
I merged the pull request using the `squash` option. Then I ran the command
```powershell
.\build.ps1 -target ReleaseNotes
```
and published the drafted release

**Comment by gep13** [comment]
@Meir017 oh, I see the problem....

https://github.com/cake-contrib/Cake.Openshift/blob/master/appveyor.yml#L19

Here you are telling AppVeyor to only build commits from branches with those names.  Your branch is called `master` not `main`.  As a result, the AppVeyor build isn't working.

I would suggest deleting the tag that was just created, both locally and on GitHub (this will cause your GitHub release to go back to draft).  Make a change to the appveyor.yml file, and commit it.  Make sure that the AppVeyor build runs.  If it does, then publish the draft release again, and then it should work.

**Pull request merged**
